language: cpp
compiler: g++
dist: trusty
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install tree cmake qt4-dev-tools qtbase5-dev
  
script:
  - export CWD=`pwd`
  - mkdir $CWD/build-release-qt5
  - cd $CWD/build-release-qt5
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DUSE_QT5=true..
  - make
  - make DESTDIR=`pwd`/pkg install
  - tree pkg
  - mkdir $CWD/build-debug-qt5
  - cd $CWD/build-debug-qt5
  - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_QT5=true..
  - make
  - mkdir $CWD/build-release-qt4
  - cd $CWD/build-release-qt4
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DUSE_QT5=false ..
  - make
  - make DESTDIR=`pwd`/pkg install
  - tree pkg
  - mkdir $CWD/build-debug-qt4
  - cd $CWD/build-debug-qt4
  - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_QT5=false ..
  - make

